---
- name: "install unbound package"
  apt:
    pkg: "unbound"
    state: "present"
- name: "ensure user exists"
  user:
    name: "{{unbound_user}}"
    group: "{{unbound_group}}"
    comment: "System user for unbound service"
    create_home: false
    home: "{{unbound_directory}}"
    shell: "/bin/false"
    state: "present"
# this allows the creation of new directories but does
# not overwrite existing system level folders
- name: "check for unbound directories"
  stat:
    path: "{{item}}"
  with_items: "{{unbound_directories|unique}}"
  register: unbound_directories_check
- name: "create unbound directories"
  file:
    path: "{{item}}"
    state: directory
    owner: "{{unbound_user}}"
    group: "{{unbound_group}}"
    mode: "0770"
  with_items: "{{unbound_directories_check.results}}"
  when: not item.stat.exists
- name: "ensure log file exists with proper perms"
  file:
    path: "{{unbound_log_file}}"
    owner: "{{unbound_user}}"
    group: "{{unbound_group}}"
    mode: "0660"
    state: "touch"
- name: "download root hints"
  get_url:
    url: "{{unbound_root_hints_url}}"
    dest: "{{unbound_root_hints_file}}"
    owner: "{{unbound_user}}"
    group: "{{unbound_group}}"
    mode: "0660"
  when: unbound_root_hints_fetch
- include: "config.yml"
- name: "update resolvconf"
  template:
    src: "resolv.conf.j2"
    dest: "/etc/resolv.conf"
    owner: "root"
    group: "root"
    mode: "0664"
  when: unbound_resolv
- name: "ensure unbound is running"
  service:
    name: "unbound"
    enabled: "yes"
    state: "started"
  register: unbound_started
- name: "reload unbound"
  service:
    name: "unbound"
    state: "reloaded"
  when: >
    not unbound_started.changed and
    (unbound_forward_zones.changed or
    remove_unbound_forward_zones.changed or
    unbound_config.changed or
    unbound_sub_configs.changed)
